/*
  CityWays JS Library
*/


/**

 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 */
var cityways={lang:{},loader:{},page:{},type:{},widget:{},template:{},model:{},helper:{},page:{main:{},routes:{}}};cityways.helper.Time={secsToLocaleString:function(a){var b=parseInt(a/3600);a=parseInt((a-3600*b)/60);return 0==b?cityways.helper.Time.minsOfHourToLocaleString(a):cityways.helper.Time.hoursToLocaleString(b)+" "+cityways.helper.Time.minsOfHourToLocaleString(a)},minsOfHourToLocaleString:function(a){if(10<=a&&20>=a)return a+" "+cityways.Language.translate("time.minutes10");var b=a%10;return 1>=b?a+" "+cityways.Language.translate("time.minute"):1<b&&5>b?a+" "+cityways.Language.translate("time.minutes"):
a+" "+cityways.Language.translate("time.minutes_ru")},hoursToLocaleString:function(a){if(5<=a&&20>=a)return a+" "+cityways.Language.translate("time.hours");var b=a%10;return 1==b?a+" "+cityways.Language.translate("time.hour"):2<=b&&5>b?a+" "+cityways.Language.translate("time.hours_ru"):a+" "+cityways.Language.translate("time.hours")}};cityways.Language={code:null,defaultCode:"ru",getCode:function(){cityways.Language.code||cityways.Language.setCode();return cityways.Language.code},setCode:function(a){var b;a||(a="msie"==cityways.BROWSER_NAME?navigator.userLanguage:navigator.language);a=a.split("-");a[0]=a[0].toLowerCase();"object"==typeof cityways.lang[a[0]]&&(b=a[0]);if(a[1]){var c=a[0]+"-"+a[1].toUpperCase();"object"==typeof cityways.lang[c]&&(b=c)}b||(cityways.Console.warn("Failed to find cityways.Lang."+a.join("-")+" dictionary, falling back to default language"),
b=cityways.Language.defaultCode);cityways.Language.code=b},translate:function(a){var b=cityways.lang[cityways.Language.getCode()];(b=b&&b[a])||(b=a);return b}};cityways.Page={Current:null,Events:function(){return cityways.Page.Current.getWidgetEventHandlers()}};cityways.Util={inherit:function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;var d,e,c=2;for(d=arguments.length;c<d;c++)e=arguments[c],"function"===typeof e&&(e=e.prototype),cityways.Util.extend(a.prototype,e)},extend:function(a,b){a=a||{};if(b){for(var c in b){var d=b[c];void 0!==d&&(a[c]=d)}!("function"==typeof window.Event&&b instanceof window.Event)&&(b.hasOwnProperty&&b.hasOwnProperty("toString"))&&(a.toString=b.toString)}return a}};cityways.type.Class=function(){var a=arguments.length,b=arguments[0],c=arguments[a-1],d="function"==typeof c.initialize?c.initialize:function(){b.prototype.initialize.apply(this,arguments)};1<a?(a=[d,b].concat(Array.prototype.slice.call(arguments).slice(1,a-1),c),cityways.Util.inherit.apply(null,a)):d.prototype=c;return d};cityways.page.MainPage=cityways.type.Class({rightPanelVisible:null,settingsPanel:null,widgetEventHandlers:null,currentCity:null,initialize:function(a){cityways.Console.log(this);cityways.Console.log("MainPage was initialized!!");this.currentCity=a.currentCity;this.widgetEventHandlers=new cityways.page.main.WidgetEventHandlers;this.settingsPanel=new cityways.page.main.SettingsPanel({availableRouteTypes:a.routeTypes});this.visibleRightPanel(!1)},getCurrentCity:function(){return this.currentCity},getWidgetEventHandlers:function(){return this.widgetEventHandlers},
getSettingsPanel:function(){return this.settingsPanel},getPathsOptions:function(){var a=this.getCurrentCity(),b=[];b.push({discount:1,route_type_id:"c_route_transition"});b.push({discount:1,route_type_id:"c_route_station_input"});b.push({discount:1,route_type_id:"c_route_station_output"});b.push({discount:0.5,route_type_id:"c_route_metro"});b.push({discount:1,route_type_id:"c_route_bus"});b.push({discount:1,route_type_id:"c_route_trolley"});return{cityID:a.id,p1:{lat:50.0253640226659,lon:36.3350757963562},
p2:{lat:50.0353179327227,lon:36.2199825018311},outTime:{dayID:"c_Sunday",timeStart:366E5},algStrategy:"c_time",usageRouteTypes:b}},visibleRightPanel:function(a){var b=cityways.Basic.ResourceURI;this.rightPanelVisible!=a&&(!0==a?($("#map_canvas").width("68%").css({cursor:"auto",backgroundColor:"rgb(226, 226, 226)"}),document.img.src=b+"themes/default/images/arrow_right.png"):($("#map_canvas").width("98.5%").css({cursor:"auto",backgroundColor:"rgb(226, 226, 226)"}),document.img.src=b+"themes/default/images/arrow_left.png"),
this.rightPanelVisible=a)}});cityways.model.Path=cityways.type.Class({pathID:null,input:null,out:null,transitions:[],routes:[],initialize:function(a){cityways.Util.extend(this,a)},getFullCost:function(){if(null==this.routes)return 0;for(var a=0,b=0;b<this.routes.length;b++)a+=this.routes[b].cost;return a},getWalkingTime:function(){for(var a=0,b=0;b<this.transitions.length;b++)a+=this.transitions[b].moveTimeSecs;a+=this.input.moveTimeSecs;a+=this.out.moveTimeSecs;return cityways.helper.Time.secsToLocaleString(a)}});cityways.page.main.SettingsPanel=cityways.type.Class({availableRouteTypes:null,initialize:function(a){this.availableRouteTypes=a.availableRouteTypes},getEnabledRouteTypes:function(){console.log(this.availableRouteTypes)},enableRouteTypeBtn:function(a,b){this.getEnabledRouteTypes();var c=cityways.Basic.ResourceURI,d=this._getRouteTypeBtnHtmlElement(a).find("img").get(0),c=c+"media/css/images/route_types/32/"+a;d.src=!0==b?c+"_selected.png":c+".png"},_getRouteTypeBtnHtmlElement:function(a){console.log($("#cways_menu_route_btn_"+
a));return $("#cways_menu_route_btn_"+a)},isEnabledRouteTypeBtn:function(a){var b=this._getRouteTypeBtnHtmlElement(a),c=cityways.Basic.ResourceURI;return-1!=b.find("img").get(0).src.indexOf(c+"media/css/images/route_types/32/"+a+".png")?!1:!0}});cityways.page.main.WidgetEventHandlers=cityways.type.Class({initialize:function(){},onRouteTypeClick:function(a,b,c,d){a=cityways.Page.Current;!0==a.getSettingsPanel().isEnabledRouteTypeBtn(b)?a.getSettingsPanel().enableRouteTypeBtn(b,!1,c):(console.log("false"),a.getSettingsPanel().enableRouteTypeBtn(b,!0,d))},_onMakeRightPanelContent:function(a,b,c){a=c["template-main-waysPanelHeader"];b=b.paths;c="";for(var d=0;d<b.length;d++){var e=new cityways.model.Path(b[d]);cityways.Console.log(e.getFullCost());
e={index:d+1,locale:cityways.Language.translate,cost:e.getFullCost(),time:e.getWalkingTime()};c+=a(e)}$("#panel_data").html(c)},_onLoadedPaths:function(a,b){var c=b.data,d={},e=0,f=this;cityways.template.HtmlTemplates.get("template-main-waysPanelHeader",function(a){e++;d["template-main-waysPanelHeader"]=a;2==e&&f._onMakeRightPanelContent(f,c,d)});cityways.template.HtmlTemplates.get("template-main-waysPanelInfo",function(a){e++;d["template-main-waysPanelInfo"]=a;2==e&&f._onMakeRightPanelContent(f,
c,d)})},onFindBtnClick:function(){var a=cityways.Page.Current,b=a.getPathsOptions(),c=document.getElementById("ways_panel");if(null!=b){c.style.display="block";c=cityways.Basic.getResourcePath()+"images/load.gif";$("#panel_data").html("<div class='loader_text'><img src='"+c+"'/></div>");$("#panel_scrollbar").tinyscrollbar_update();a.visibleRightPanel(!0);var d=this;cityways.Console.log("onFindBtnClick");(new cityways.loader.PathsLoader).findShortestPaths(b,function(a){cityways.Console.log("findShortestPaths");
d._onLoadedPaths(d,a)})}},on_selectDetailWay:function(){cityways.Console.log("OK")}});void 0===cityways.Console&&(cityways.Console={log:function(){}});cityways.template.HtmlTemplates={_templates:{},get:function(a,b){var c=cityways.template.HtmlTemplates._templates;if(void 0===c[a]){var d=new cityways.loader.TemplatesLoader,e=cityways.template.HtmlTemplates._getFileByTemplateName(a);d.loadHtmlTemplates(e,function(d){cityways.Util.extend(c,d);b(c[a])})}else b(c[a])},_getFileByTemplateName:function(){return"main"}};(function(){var a=!0;void 0===window.cityways&&(a=!1);if(!a){for(var a="cityways/Namespace.js cityways/helper/Time.js cityways/Language.js cityways/Page.js cityways/Util.js cityways/type/Class.js cityways/page/MainPage.js cityways/model/Path.js cityways/page/main/SettingsPanel.js cityways/page/main/WidgetEventHandlers.js cityways/Console.js cityways/template/HtmlTemplates.js cityways/Basic.js cityways/lang/ru.js cityways/lang/en.js cityways/lang/uk.js cityways/loader/PathsLoader.js cityways/loader/TemplatesLoader.js cityways/WidgetMap.js".split(" "),
b=Array(a.length),c=/(^|(.*?\/))(CityWays[^\/]*?\.js)(\?|$)/,d=document.getElementsByTagName("script"),e,f="",g=0,h=d.length;g<h;g++)if(e=d[g].getAttribute("src"))if(e=e.match(c)){f=e[1];break}c=f+"/";d=0;for(f=a.length;d<f;d++)b[d]="<script src='"+c+a[d]+"'>\x3c/script>";0<b.length&&document.write(b.join(""))}})();cityways.Basic={ServerHost:"http://ways.in.ua",Theme:"default",ResourceURI:"/",VERSION_NUMBER:"Release 2.13 dev",_getScriptLocation:function(a){a=RegExp("(^|(.*?\\/))("+a+"[^\\/]*?\\.js)(\\?|$)");for(var b=document.getElementsByTagName("script"),c,d="",e=0,f=b.length;e<f;e++)if(c=b[e].getAttribute("src"))if(c=c.match(a)){d=c[1];break}return d},getResourcePath:function(){return cityways.Basic.ResourceURI+"themes/"+cityways.Basic.Theme+"/"}};
(function(){cityways.Basic.ResourceURI=cityways.Basic._getScriptLocation("MainPage");cityways.Console.log(cityways.Basic.ResourceURI)})();cityways.lang.uk={path_time:"\u0427\u0430\u0441 \u0432 \u0434\u043e\u0440\u043e\u0437i",cost:"\u0412\u0430\u0440\u0442i\u0441\u0442\u044c:",time:"\u0427\u0430\u0441 \u0443 \u0434\u043e\u0440\u043e\u0437i: ",UAH:"\u0433\u0440\u043d","time.minute":"\u0445\u0432\u0438\u043b\u0438\u043d\u0430","time.minutes10":"\u0445\u0432\u0438\u043b\u0438\u043d","time.minutes":"\u0445\u0432\u0438\u043b\u0438\u043d\u0438","time.minutes_ru":"\u0445\u0432\u0438\u043b\u0438\u043d"};cityways.lang.ru={path_time:"\u0412\u0440\u0435\u043c\u044f \u0432 \u043f\u0443\u0442\u0438",cost:"\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c:",time:"\u0412\u0440\u0435\u043c\u044f \u0432 \u043f\u0443\u0442\u0438: ",UAH:"\u0433\u0440\u043d","time.minute":"\u043c\u0438\u043d\u0443\u0442\u0430","time.minutes10":"\u043c\u0438\u043d\u0443\u0442","time.minutes":"\u043c\u0438\u043d\u0443\u0442\u044b","time.minutes_ru":"\u043c\u0438\u043d\u0443\u0442"};cityways.loader.PathsLoader=cityways.type.Class({initialize:function(){},findShortestPaths:function(a,b){$.ajax({url:cityways.Basic.ServerHost+"/paths/find.json",type:"POST",data:{data:$.toJSON(a)},success:function(a){cityways.Console.log("findShortestPaths");a=$.parseJSON(a);if(null==b)throw Error("resultFunc was not defined");b({data:a})}})}});cityways.WidgetMap=cityways.type.Class({initialize:function(){console.log("map was initialized")}});cityways.lang.en={path_time:"Path time",cost:"Coast",time:"Path time",UAH:"UAH","time.minute":"minute","time.minutes10":"minutes","time.minutes":"minutes","time.minutes_ru":"minutes",unhandledRequest:"Unhandled request return ${statusText}",Permalink:"Permalink",Overlays:"Overlays","Base Layer":"Base Layer",noFID:"Can't update a feature for which there is no FID.",browserNotSupported:"Your browser does not support vector rendering. Currently supported renderers are:\n${renderers}",minZoomLevelError:"The minZoomLevel property is only intended for use with the FixedZoomLevels-descendent layers. That this wfs layer checks for minZoomLevel is a relic of thepast. We cannot, however, remove it without possibly breaking OL based applications that may depend on it. Therefore we are deprecating it -- the minZoomLevel check below will be removed at 3.0. Please instead use min/max resolution setting as described here: http://trac.openlayers.org/wiki/SettingZoomLevels",
commitSuccess:"WFS Transaction: SUCCESS ${response}",commitFailed:"WFS Transaction: FAILED ${response}",googleWarning:"The Google Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the Google Maps library script was either not included, or does not contain the correct API key for your site.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/Google' target='_blank'>click here</a>",
getLayerWarning:"The ${layerType} Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the ${layerLib} library script was not correctly included.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/${layerLib}' target='_blank'>click here</a>","Scale = 1 : ${scaleDenom}":"Scale = 1 : ${scaleDenom}",W:"W",E:"E",N:"N",S:"S",Graticule:"Graticule",
reprojectDeprecated:"You are using the 'reproject' option on the ${layerName} layer. This option is deprecated: its use was designed to support displaying data over commercial basemaps, but that functionality should now be achieved by using Spherical Mercator support. More information is available from http://trac.openlayers.org/wiki/SphericalMercator.",methodDeprecated:"This method has been deprecated and will be removed in 3.0. Please use ${newMethod} instead.",end:""};cityways.loader.TemplatesLoader=cityways.type.Class({initialize:function(){},loadHtmlTemplates:function(a,b){$.ajax({url:cityways.Basic.ResourceURI+"themes/"+cityways.Basic.Theme+"/templates/"+a+".xml",success:function(a){if(null==b)throw Error("callback was not defined");a=a.getElementsByTagName("template");for(var d={},e=0;e<a.length;e++)try{cityways.Console.log(a[e].textContent);cityways.Console.log(a[e].getAttribute("id"));var f=a[e].getAttribute("id"),g=_.template(a[e].textContent);d[f]=g;cityways.Console.log("ok")}catch(h){}b(d)}})}});
