/*
  CityWays JS Library
*/


/**

 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 */
var cityways={lang:{},loader:{},page:{},type:{},widget:{},template:{},page:{main:{},routes:{}}};cityways.Language={code:null,defaultCode:"En",getCode:function(){cityways.Language.code||cityways.Language.setCode();return cityways.Language.code},setCode:function(a){var b;a||(a="msie"==cityways.BROWSER_NAME?navigator.userLanguage:navigator.language);a=a.split("-");a[0]=a[0];"object"==typeof cityways.lang[a[0]]&&(b=a[0]);if(a[1]){var c=a[0]+"-"+a[1].toUpperCase();"object"==typeof cityways.lang[c]&&(b=c)}b||(cityways.Console.warn("Failed to find cityways.Lang."+a.join("-")+" dictionary, falling back to default language"),
b=cityways.Language.defaultCode);cityways.Language.code=b},translate:function(a){var b=cityways.lang[cityways.Language.getCode()];(b=b&&b[a])||(b=a);return b}};cityways.Util={inherit:function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;var d,e,c=2;for(d=arguments.length;c<d;c++)e=arguments[c],"function"===typeof e&&(e=e.prototype),cityways.Util.extend(a.prototype,e)},extend:function(a,b){a=a||{};if(b){for(var c in b){var d=b[c];void 0!==d&&(a[c]=d)}!("function"==typeof window.Event&&b instanceof window.Event)&&(b.hasOwnProperty&&b.hasOwnProperty("toString"))&&(a.toString=b.toString)}return a}};cityways.type.Class=function(){var a=arguments.length,b=arguments[0],c=arguments[a-1],d="function"==typeof c.initialize?c.initialize:function(){b.prototype.initialize.apply(this,arguments)};1<a?(a=[d,b].concat(Array.prototype.slice.call(arguments).slice(1,a-1),c),cityways.Util.inherit.apply(null,a)):d.prototype=c;return d};cityways.page.MainPage=cityways.type.Class({settingsPanel:null,widgetEventHandlers:null,currentCity:null,initialize:function(a){cityways.Console.log(this);cityways.Console.log("MainPage was initialized!!");this.currentCity=a.currentCity;this.widgetEventHandlers=new cityways.page.main.WidgetEventHandlers;this.settingsPanel=new cityways.page.main.SettingsPanel({availableRouteTypes:a.routeTypes})},getCurrentCity:function(){return this.currentCity},getWidgetEventHandlers:function(){return this.widgetEventHandlers},
getSettingsPanel:function(){return this.settingsPanel},getPathsOptions:function(){var a=this.getCurrentCity(),b=[];b.push({discount:1,route_type_id:"c_route_transition"});b.push({discount:1,route_type_id:"c_route_station_input"});b.push({discount:1,route_type_id:"c_route_station_output"});b.push({discount:0.5,route_type_id:"c_route_metro"});b.push({discount:1,route_type_id:"c_route_bus"});b.push({discount:1,route_type_id:"c_route_trolley"});return{cityID:a.id,p1:{lat:50.0253640226659,lon:36.3350757963562},
p2:{lat:50.0353179327227,lon:36.2199825018311},outTime:{dayID:"c_Sunday",timeStart:366E5},algStrategy:"c_time",usageRouteTypes:b}}});cityways.WidgetMap=cityways.type.Class({initialize:function(){console.log("map was initialized")}});cityways.page.main.SettingsPanel=cityways.type.Class({availableRouteTypes:null,initialize:function(a){this.availableRouteTypes=a.availableRouteTypes},getEnabledRouteTypes:function(){console.log(this.availableRouteTypes)},enableRouteTypeBtn:function(a,b){this.getEnabledRouteTypes();var c=cityways.Basic.ResourceURI,d=this._getRouteTypeBtnHtmlElement(a).find("img").get(0),c=c+"media/css/images/route_types/32/"+a;d.src=!0==b?c+"_selected.png":c+".png"},_getRouteTypeBtnHtmlElement:function(a){console.log($("#cways_menu_route_btn_"+
a));return $("#cways_menu_route_btn_"+a)},isEnabledRouteTypeBtn:function(a){var b=this._getRouteTypeBtnHtmlElement(a),c=cityways.Basic.ResourceURI;return-1!=b.find("img").get(0).src.indexOf(c+"media/css/images/route_types/32/"+a+".png")?!1:!0}});void 0===cityways.Console&&(cityways.Console={log:function(){}});cityways.page.main.WidgetEventHandlers=cityways.type.Class({initialize:function(){},onRouteTypeClick:function(a,b,c,d){a=cityways.Page.Current;!0==a.getSettingsPanel().isEnabledRouteTypeBtn(b)?a.getSettingsPanel().enableRouteTypeBtn(b,!1,c):(console.log("false"),a.getSettingsPanel().enableRouteTypeBtn(b,!0,d))},onFindBtnClick:function(){var a=cityways.Page.Current.getPathsOptions(),b=document.getElementById("ways_panel");null!=a&&(b.style.display="block",cityways.template.HtmlTemplates.get("template-main-waysPanel",
function(a){$("#panel_data").html(a({value:"test"}));cityways.Console.log(a)}))}});cityways.template.HtmlTemplates={_templates:{},get:function(a,b){var c=cityways.template.HtmlTemplates._templates;if(void 0===c[a]){var d=new cityways.loader.TemplatesLoader,e=cityways.template.HtmlTemplates._getFileByTemplateName(a);d.loadHtmlTemplates(e,function(d){cityways.Util.extend(c,d);b(c[a])})}else b(c[a])},_getFileByTemplateName:function(){return"main"}};cityways.Basic={Theme:"default",ResourceURI:"/",VERSION_NUMBER:"Release 2.13 dev",_getScriptLocation:function(a){a=RegExp("(^|(.*?\\/))("+a+"[^\\/]*?\\.js)(\\?|$)");for(var b=document.getElementsByTagName("script"),c,d="",e=0,f=b.length;e<f;e++)if(c=b[e].getAttribute("src"))if(c=c.match(a)){d=c[1];break}return d}};(function(){cityways.Basic.ResourceURI=cityways.Basic._getScriptLocation("MainPage");cityways.Console.log(cityways.Basic.ResourceURI)})();cityways.loader.PathsLoader=cityways.type.Class({initialize:function(){},findShortestPaths:function(a,b){$.ajax({url:cityways.ResourceURI+"paths/find.json",type:"POST",data:{data:$.toJSON(a)},success:function(a){if(null==b)throw Error("resultFunc was not defined");b({data:a})},dataType:"application/json"})}});cityways.loader.TemplatesLoader=cityways.type.Class({initialize:function(){},loadHtmlTemplates:function(a,b){$.ajax({url:cityways.Basic.ResourceURI+"themes/"+cityways.Basic.Theme+"/templates/"+a+".xml",success:function(a){if(null==b)throw Error("callback was not defined");a=a.getElementsByTagName("template");for(var d={},e=0;e<a.length;e++)try{cityways.Console.log(a[e].textContent);cityways.Console.log(a[e].getAttribute("id"));var f=a[e].getAttribute("id"),g=_.template(a[e].textContent);d[f]=g;cityways.Console.log("ok")}catch(h){}b(d)}})}});cityways.Page={Current:null,Events:function(){return cityways.Page.Current.getWidgetEventHandlers()}};cityways.lang.En={unhandledRequest:"Unhandled request return ${statusText}",Permalink:"Permalink",Overlays:"Overlays","Base Layer":"Base Layer",noFID:"Can't update a feature for which there is no FID.",browserNotSupported:"Your browser does not support vector rendering. Currently supported renderers are:\n${renderers}",minZoomLevelError:"The minZoomLevel property is only intended for use with the FixedZoomLevels-descendent layers. That this wfs layer checks for minZoomLevel is a relic of thepast. We cannot, however, remove it without possibly breaking OL based applications that may depend on it. Therefore we are deprecating it -- the minZoomLevel check below will be removed at 3.0. Please instead use min/max resolution setting as described here: http://trac.openlayers.org/wiki/SettingZoomLevels",
commitSuccess:"WFS Transaction: SUCCESS ${response}",commitFailed:"WFS Transaction: FAILED ${response}",googleWarning:"The Google Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the Google Maps library script was either not included, or does not contain the correct API key for your site.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/Google' target='_blank'>click here</a>",
getLayerWarning:"The ${layerType} Layer was unable to load correctly.<br><br>To get rid of this message, select a new BaseLayer in the layer switcher in the upper-right corner.<br><br>Most likely, this is because the ${layerLib} library script was not correctly included.<br><br>Developers: For help getting this working correctly, <a href='http://trac.openlayers.org/wiki/${layerLib}' target='_blank'>click here</a>","Scale = 1 : ${scaleDenom}":"Scale = 1 : ${scaleDenom}",W:"W",E:"E",N:"N",S:"S",Graticule:"Graticule",
reprojectDeprecated:"You are using the 'reproject' option on the ${layerName} layer. This option is deprecated: its use was designed to support displaying data over commercial basemaps, but that functionality should now be achieved by using Spherical Mercator support. More information is available from http://trac.openlayers.org/wiki/SphericalMercator.",methodDeprecated:"This method has been deprecated and will be removed in 3.0. Please use ${newMethod} instead.",end:""};
